version: '3.8'
services:

  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - './:/code'
      - './docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'
    networks:
      - code-network

  nginx:
    image: 'nginx:latest'
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - './docker/nginx/public.conf:/etc/nginx/conf.d/public.conf'
      - './docker/nginx/api.conf:/etc/nginx/conf.d/api.conf'
      - './:/code'
    links:
      - php
    networks:
      - code-network

  mysql:
    image: mysql:8
    volumes:
      - ./docker/mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'catsdb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - code-network

networks:
  code-network:
    driver: bridge
